// Embeds the simulator page (packages/simulator/public) into a TypeScript module, so the Lambda bundle
// carries it without copying files around. Run after changing the page: node scripts/embed-ui.mjs
// A test (packages/simulator/src/ui-assets.test.ts) fails when the generated file is stale.
import { readFileSync, writeFileSync } from 'node:fs';

const FILES = {
  '/index.html': ['index.html', 'text/html; charset=utf-8'],
  '/app.js': ['app.js', 'text/javascript; charset=utf-8'],
  '/styles.css': ['styles.css', 'text/css; charset=utf-8'],
};

const assets = Object.fromEntries(
  Object.entries(FILES).map(([route, [file, contentType]]) => [
    route,
    { contentType, body: readFileSync(`packages/simulator/public/${file}`, 'utf8') },
  ]),
);

writeFileSync(
  'packages/simulator/src/ui-assets.generated.ts',
  `// GENERATED by scripts/embed-ui.mjs from packages/simulator/public. Do not edit by hand.\n` +
    `export const UI_ASSETS: Record<string, { contentType: string; body: string }> = ${JSON.stringify(assets, null, 2)};\n`,
);
console.log('embedded', Object.keys(assets).join(', '));
